language: c
script:
  # My raytrace project depends on my c-examples project. I'm
  # not sure if this is the best way to handle the dependency.
  - git clone https://github.com/bjourne/c-examples
  - cd c-examples
  - ./waf configure --prefix=/tmp/bl
  - ./waf build install

os:
  - linux
compiler:
  - clang
  - gcc
